### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Hefaustas** [AttorneyOnlineVidya/tsuserver3#27]
When I press start_server.py it launches CMD for a second and then closes.

**Comment by oldmud0** [comment]
Not a bug. Please read the readme on how to set it up correctly, or at least show its output by explicitly running it from the command prompt.

**Comment by Hefaustas** [comment]
cmd is outputting "UnboundLocalError: local variable 'conn' reference before assignment"

**Comment by Hefaustas** [comment]
Ok, I'm stupid I just realized there's a thread just for this issue...
