### ISSUE TITLE
"Offline" server

### ISSUE THREAD

**Issue by mautix** [AttorneyOnlineVidya/tsuserver3#29]
I made a server to play with some friends, but only i can enter the Server, because to the other people says its "Offline", someone can help?

(Sorry if i have bad english)

**Comment by oldmud0** [comment]
First: you are in the [wrong repo](https://github.com/AttorneyOnline/tsuserver3).
Second: this is not the place to get tech support. Please get it from the [official Discord server](https://discord.gg/wWvQ3pw).
Third: have you read the [How to Server](https://docs.google.com/document/d/1xOd7SDCBmSA0RM8M7JX7xACA4YUsQn72Bob9HBOzhVM/edit) guide? It is in the FAQ of the official website.

**Comment by mautix** [comment]
Oh.. Sorry, but Thanks too!
